import { readFile, writeFile } from 'node:fs/promises';
const data = JSON.parse(await readFile('src/data/published/catalogue.json', 'utf8'));
const geo = JSON.parse(await readFile('src/data/published/geography.json', 'utf8'));
const commercial = JSON.parse(await readFile('src/data/published/commercial-off.json', 'utf8'));
const categories = ['spices', 'vegetables', 'fish'].map((id) => [
  id,
  data.products.filter((p) => p.categoryId === id).length,
]);
const report = `# Qualité et couverture réelle\n\nInstantané du 4 octobre 2026.\n\n- ${data.products.length} fiches publiques, ${data.images.length} photographies créditées, ${data.names.length} assertions linguistiques documentées.\n- Répartition réelle : ${categories.map(([id, count]) => `${id} ${count}`).join(', ')}. La cible 40/40/20 n’est pas revendiquée comme atteinte.\n- ${commercial.references.length} références Open Food Facts distinctes ; aucun lien ingrédient validé et aucune photo d’emballage importée.\n- 20 pays africains explorables et 5 contextes européens séparés. Aucun usage national ou régional des noms n’est prouvé dans cet instantané : zéro correspondance contextualisée publiée.\n- ${geo.regions.length} subdivisions ADM1 : CMR 10 (2016), CIV 14 districts (2016), MAR 12 (2017), SEN 14 (2019). Vérification des champs ISO/ADM1, compte cohérent et noms inspectés ; pas de certification de l’actualité administrative.\n- 6 illustrations exclues après examen visuel : poivre noir, Capsicum annuum, cumin, anis, sardine européenne, poisson-chat africain. Candidats et assets conservés hors du site public.\n\n## Statuts et preuves\n\nLes names documentés portent une preuve source/révision/pointeur JSON. Aucune assertion n’est marquée reviewed : l’import et la lecture d’une image par l’assistant ne simulent pas un examen humain culturel. Les candidates/rejected ne sont pas exposés par la recherche publique.\n\n## Limites importantes\n\nLe lot est une base taxonomique et linguistique, pas un dictionnaire validé des pratiques alimentaires africaines. Les photos montrent parfois fleurs ou plantes entières : ce n’est pas une forme de vente prouvée. Les usages culinaires et les relations entre formes restent à documenter. Aucun poisson de marché n’est identifié automatiquement. Un résultat approximatif est annoncé comme tel.\n\nLes régions et les pays sont des outils de navigation. Une langue ne prouve jamais un pays ; une présence botanique n’est pas une preuve de consommation. Le manque de données produit un état vide explicite, pas une attribution automatique.\n\n## Enrichissement\n\nVoir CONTENT_BACKLOG.md pour les sources ethnobotaniques, formes alimentaires, ambiguïtés, marques, droits d’emballages et appellations contextualisées. Les compteurs de l’interface dérivent des données publiées.\n`;
await writeFile('docs/DATA_QUALITY.md', report);
console.log('Quality report generated from published data.');
